name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del codice
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurazione di Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 
          cache: 'npm'

      # Installazione delle dipendenze
      - name: Install dependencies
        run: npm install

      # Esecuzione dei test
      - name: Run tests
        run: npm test

      # Deploy su Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: ./
